version: "3.8"
services:
  devcontainer:
    image: node:20-bullseye
    volumes:
      - ../..:/workspaces:cached
      # Avoid setting up Git in the container
      - ~/.gitconfig:/root/.gitconfig
      # Avoids setting up ssh in container
      - ~/.ssh:/root/.ssh
    command: sleep infinity
